version: '3'

networks:
  proxy:
    name: proxy
    external: true
  internal:
    internal: true

services:
  wp:
    extends:
      file: docker/wp/docker-compose.override.yaml
      service: wp
  db:
    extends:
      file: docker/db/docker-compose.override.yaml
      service: db
  dba:
    extends:
      file: docker/dba/docker-compose.override.yaml
      service: dba
  mailhog:
    extends:
      file: docker/mailhog/docker-compose.override.yaml
      service: mailhog
